### ISSUE TITLE
Make data model object properties settable

### ISSUE THREAD

**Issue by blthiewes** [voucherifyio/voucherify-dotNET-sdk#24] opened 2018-12-26 18:47 UTC
To unit test mappings of the voucherify objects to our internal DTO objects, I'd like to be able new up an object and set it's properties. Instead, I have to use a mocking framework to test.

**Comment by bandraszyk** [comment] 2018-12-27 09:50
From SDK perspective this change does not make any sense as by design we want to keep data retrieved from our system readonly. Only entities that can be changed includes `set` properties. If you do not want to use any mocking framework you can still use https://www.newtonsoft.com/json lib to deserialise JSON objects.

I'm closing the issue as we do not plan to provide any changes in sdk.

**Closed by bandraszyk** 2018-12-27 09:50 UTC

**Comment by blthiewes** [comment] 2018-12-27 12:40
Please add interfaces to your objects so that we can mock then.

**Comment by bandraszyk** [comment] 2018-12-27 15:39
@blthiewes Sorry but we are not going to introduce any changes that would break other customers integrations. As you mentioned you are not blocked anyhow by this as you still have an option to use mocking framework which were created to situations just like that. If you are not willing to go for mocking framework you can use some methods from `System.Reflection` namespece to make it works:

```
DataModel.Voucher v = new DataModel.Voucher();
typeof(DataModel.Voucher).GetProperty("Code").SetValue(v, "testcode");
```
